USA_STATES = {
    'Alabama': {'Standard': 'Ala.',
                'Postal': 'AL',
                'Region': 'South, S, East South Central'},
    'Alaska': {'Standard': 'Alaska',
                'Postal': 'AK',
                'Region': 'West, W, Mountain'},
    'Arizona': {'Standard': 'Ariz.',
                'Postal': 'AZ',
                'Region': 'West, W, Mountain'},
    'Arkansas': {'Standard': 'Ark.',
                'Postal': 'AR',
                'Region': 'South, S, West South Central'},
    'California': {'Standard': 'Calif.',
                'Postal': 'CA',
                'Region': 'West, W, Pacific'},
    'Colorado': {'Standard': 'Colo.',
                'Postal': 'CO',
                'Region': 'West, W, Mountain'},
    'Connecticut': {'Standard': 'Conn.',
                'Postal': 'CT',
                'Region': 'Northeast, NE, New England'},
    'Delaware': {'Standard': 'Del.',
                'Postal': 'DE',
                'Region': 'South, S, South Atlantic'},
    'District of Columbia': {'Standard': 'D.C.',
                'Postal': 'DC',
                'Region': 'South, S, South Atlantic'},
    'Florida': {'Standard': 'Fla.',
                'Postal': 'FL',
                'Region': 'South, S, South Atlantic'},
    'Georgia': {'Standard': 'Ga.',
                'Postal': 'GA',
                'Region': 'South, S, South Atlantic'},
    'Hawaii': {'Standard': 'Hawaii',
                'Postal': 'HI',
                'Region': 'West, W, Pacific'},
    'Idaho': {'Standard': 'Idaho.',
                'Postal': 'ID',
                'Region': 'West, W, Mountain'},
    'Illinois': {'Standard': 'Ill.',
                'Postal': 'IL',
                'Region': 'Midwest, East North Central'},
    'Indiana': {'Standard': 'Ind.',
                'Postal': 'IN',
                'Region': 'Midwest, East North Central'},
    'Iowa': {'Standard': 'Iowa',
                'Postal': 'IA',
                'Region': 'Midwest, West North Central'},
    'Kansas': {'Standard': 'Kan.',
                'Postal': 'KS',
                'Region': 'Midwest, West North Central'},
    'Kentucky': {'Standard': 'Ky.',
                'Postal': 'KY',
                'Region': 'South, East South Central'},
    'Louisiana': {'Standard': 'La.',
                'Postal': 'LA',
                'Region': 'South, West South Central'},
    'Maine': {'Standard': 'Maine',
                'Postal': 'ME',
                'Region': 'Northeast, NE, New England'},
    'Maryland': {'Standard': 'Md',
                'Postal': 'MD',
                'Region': 'South, S, South Atlantic'},
    'Massachusetts': {'Standard': 'Mass.',
                'Postal': 'MA',
                'Region': 'Northeast, NE, New England'},
    'Michigan': {'Standard': 'Mich.',
                'Postal': 'MI',
                'Region': 'Midwest, East North Central'},
    'Minnesota': {'Standard': 'Minn.',
                'Postal': 'MN',
                'Region': 'Midwest, West North Central'},
    'Mississippi': {'Standard': 'Miss.',
                'Postal': 'MS',
                'Region': 'South, S, East South Central'},
    'Missouri': {'Standard': 'Mo.',
                'Postal': 'MO',
                'Region': 'Midwest, West North Central'},
    'Montana': {'Standard': 'Mont.',
                'Postal': 'MT',
                'Region': 'West, W, Mountain'},
    'Nebraska': {'Standard': 'Neb.',
                'Postal': 'NE',
                'Region': 'Midwest, West North Central'},
    'Nevada': {'Standard': 'Neb.',
                'Postal': 'NE',
                'Region': 'West, W, Mountain'},
    'New Hampshire': {'Standard': 'N.H.',
                'Postal': 'NH',
                'Region': 'Northeast, NE, New England'},
    'New Jersey': {'Standard': 'N.J.',
                'Postal': 'NJ',
                'Region': 'Northeast, NE, Middle Atlantic'},
    'New Mexico': {'Standard': 'N.M.',
                'Postal': 'NM',
                'Region': 'West, W, Mountain'},
    'New York': {'Standard': 'N.Y.',
                'Postal': 'NY',
                'Region': 'Northeast, NE, Middle Atlantic'},
    'North Carolina': {'Standard': 'N.C.',
                'Postal': 'NC',
                'Region': 'South, S, South Atlantic'},
    'North Dakota': {'Standard': 'N.D.',
                'Postal': 'ND',
                'Region': 'Midwest, West North Central'},
    'Ohio': {'Standard': 'Ohio',
                'Postal': 'OH',
                'Region': 'Midwest, East North Central'},
    'Oklahoma': {'Standard': 'Okla.',
                'Postal': 'OK',
                'Region': 'South, S, West South Central'},
    'Oregon': {'Standard': 'Ore.',
                'Postal': 'OR',
                'Region': 'West, W, Pacific'},
    'Pennsylvania': {'Standard': 'P.a',
                'Postal': 'PA',
                'Region': 'Northeast, NE, Middle Atlantic'},    
    'Rhode Island': {'Standard': 'R.I.',
                'Postal': 'RI',
                'Region': 'Northeast, NE, New England'},
    'South Carolina': {'Standard': 'S.C.',
                'Postal': 'SC',
                'Region': 'South, S, South Atlantic'},
    'South Dakota': {'Standard': 'S.D.',
                'Postal': 'SD',
                'Region': 'Midwest, West North Central'},
    'Tennessee': {'Standard': 'Tenn.',
                'Postal': 'TN',
                'Region': 'South, S, East South Central'},
    'Texas': {'Standard': 'Texas',
                'Postal': 'TX',
                'Region': 'South, S, West South Central'},
    'Utah': {'Standard': 'Utah',
                'Postal': 'UT',
                'Region': 'West, W, Mountain'},
    'Vermont': {'Standard': 'Vt.',
                'Postal': 'VT',
                'Region': 'Northeast, NE, New England'},
    'Virginia': {'Standard': 'Va.',
                'Postal': 'VA',
                'Region': 'South, S, South Atlantic'},
    'Washington': {'Standard': 'Wash.',
                'Postal': 'WA',
                'Region': 'West, W, Pacific'},
    'West Virginia': {'Standard': 'W.Va.',
                'Postal': 'WV',
                'Region': 'South, S, South Atlantic'},
    'Wisconsin': {'Standard': 'Wis.',
                'Postal': 'WI',
                'Region': 'Midwest, East North Central'},
    'Wyoming': {'Standard': 'Wyo.',
                'Postal': 'WY',
                'Region': 'West, W, Mountain'},
}